config/routes.rb
Rails.application.routes.draw do
  #constraints(subdomain: 'admin') do
    scope module: 'admin' do
      resources :controls
      resources :device_types, except: :show
      resources :devices, except: :show
      root 'devices#index', as: 'admin_root'
    end
  #end

  constraints(subdomain: 'app') do
    scope module: 'frontend' do
      root 'devices#index', as: 'frontend_root'
      resources :devices, as: 'app_devices', only: [:index, :update]
    end
  end
end

app/models/control_item.rb
class ControlItem < ActiveRecord::Base
  KINDS = %w(select slider button)

  belongs_to :device_type

  def slider?
    kind == 'slider'
  end

  def select_options
    value.split(',')
  end

  def api_verb
    api_endpoint.to_s.strip.split.first
  end

  def api_url
    api_endpoint.to_s.strip.split.last
  end
end

app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :device_type

  serialize :controls_state, Hash

  def control_items?
   device_type.control_items.any?
  end

  def control_value_for(control_item)
    controls_state[control_item.name.parameterize]
  end
end

app/models/device_type.rb
class DeviceType < ActiveRecord::Base
  has_many :control_items, dependent: :destroy
  has_many :devices, dependent: :destroy

  accepts_nested_attributes_for :control_items, reject_if: :all_blank, allow_destroy: true
end

app/controllers/admin/device_types_controller.rb
class Admin::DeviceTypesController < ApplicationController
  before_action :set_device_type, only: [:show, :edit, :update, :destroy]

  def index
    @device_types = DeviceType.all.order(:name)
  end

  def new
    @device_type = DeviceType.new
  end

  def create
    @device_type = DeviceType.new(device_type_params)

    if @device_type.save
      redirect_to edit_device_type_url(@device_type), notice: 'Device type was successfully created.'
    else
      render :new
    end
  end

  def update
    if @device_type.update(device_type_params)
      redirect_to edit_device_type_url(@device_type), notice: 'Device type was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @device_type.destroy

    redirect_to device_types_url, notice: 'Device type was successfully destroyed.'
  end

  private

  def set_device_type
    @device_type = DeviceType.find(params[:id])
  end

  def device_type_params
    params.require(:device_type).permit(
      :name,
      control_items_attributes: [
        :id,
        :kind,
        :name,
        :value,
        :api_endpoint,
        :_destroy
      ]
    )
  end
end

app/controllers/admin/devices_controller.rb
class Admin::DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  def index
    @devices = Device.all.order(:name)
  end

  def new
    @device = Device.new
  end

  def create
    @device = Device.new(device_params)

    if @device.save
      notice = 'Device was successfully created.' unless params[:device_type_change]

      redirect_to edit_device_url(@device), notice: notice
    else
      render :new
    end
  end

  def update
    if @device.update(device_params)
      notice = 'Device was successfully updated.' unless params[:device_type_change]

      redirect_to edit_device_url(@device), notice: notice
    else
      render :edit
    end
  end

  def destroy
    @device.destroy

    redirect_to devices_url, notice: 'Device was successfully destroyed.'
  end

  private

  def set_device
    @device = Device.find(params[:id])
  end

  def device_params
    params.require(:device).permit(:name, :ip_address, :device_type_id).tap do |whitelisted|
     whitelisted[:controls_state] = params[:device][:controls_state]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  skip_before_filter :verify_authenticity_token
end

app/controllers/device_types_controller.rb
class DeviceTypesController < ApplicationController
  before_action :set_device_type, only: [:show, :edit, :update, :destroy]

  def index
    @device_types = DeviceType.all.order(:name)
  end

  def new
    @device_type = DeviceType.new
  end

  def create
    @device_type = DeviceType.new(device_type_params)

    respond_to do |format|
      if @device_type.save
        format.html { redirect_to @device_type, notice: 'Device type was successfully created.' }
        format.json { render :show, status: :created, location: @device_type }
      else
        format.html { render :new }
        format.json { render json: @device_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @device_type.update(device_type_params)
        format.html { redirect_to @device_type, notice: 'Device type was successfully updated.' }
        format.json { render :show, status: :ok, location: @device_type }
      else
        format.html { render :edit }
        format.json { render json: @device_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @device_type.destroy
    respond_to do |format|
      format.html { redirect_to device_types_url, notice: 'Device type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_device_type
    @device_type = DeviceType.find(params[:id])
  end

  def device_type_params
    params.require(:device_type).permit(:name, control_items_attributes: [ :id, :kind, :name, :value, :_destroy ])
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  def index
    @devices = Device.all.order(:name)
  end

  def new
    @device = Device.new
  end

  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_device
    @device = Device.find(params[:id])
  end

  def device_params
    params.require(:device).permit(:name, :ip_address, :device_type_id).tap do |whitelisted|
     whitelisted[:controls_state] = params[:device][:controls_state]
    end
  end
end

app/controllers/frontend/devices_controller.rb
class Frontend::DevicesController < ApplicationController
  layout 'frontend'

  def index
    @devices = Device.all.includes(device_type: :control_items).order(:name)
  end

  def update
    @device = Device.find(params[:id])

    respond_to do |format|
      if @device.update(device_params)
        format.json { render :show, status: :ok, location: @device }
      else
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def device_params
    params.require(:device).permit().tap do |whitelisted|
     whitelisted[:controls_state] = params[:device][:controls_state]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/controls_helper.rb
module ControlsHelper
end

app/helpers/device_types_helper.rb
module DeviceTypesHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/frontend_helper.rb
module FrontendHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/_messages.html.haml
#messages{ data: { close: "true",
                   target: "#messages" } }
  - if notice || alert
    .alert{ class: "#{'alert-info' if notice} #{'alert-danger' if alert}" }
      .container
        = notice.presence || alert.presence
        .pull-right
          = link_to request.original_fullpath do
            %i.fa.fa-times.fa-1

app/views/admin/_navbar.html.haml
%nav.navbar.navbar-default{role: "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => "#main-menu", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

    #main-menu.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to 'Devices', devices_url
        %li
          = link_to 'Devices Types', device_types_url
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to 'http://app.kalm.pl', { target: '_blank' } do
            %span.glyphicon.glyphicon-new-window
            Open Frontend App

  = render "admin/messages"

app/views/admin/controls/_button.html.haml
%td
  = control_item.kind.capitalize
%td
  = control_item.name
%td
%td
  = control_item.api_endpoint

app/views/admin/controls/_select.html.haml
%td
  = control_item.kind.capitalize
%td
  = control_item.name
%td
  = select_tag("device[controls_state][#{control_item.name.parameterize}]", options_for_select(control_item.select_options, control_item_value))
%td
  = control_item.api_endpoint

app/views/admin/controls/_slider.html.haml
%td
  = control_item.kind.capitalize
%td
  = control_item.name
%td
  = range_field_tag("device[controls_state][#{control_item.name.parameterize}]", control_item_value, in: 1..100)
%td
  = control_item.api_endpoint

app/views/admin/device_types/_control_item_fields.html.haml
.nested-fields
  %table.table.table-striped
    %thead
      %tr
        %th Kind
        %th Name
        %th Value
        %th API Endpoint
        %th Action
    %tbody
      %tr
        %td
          .form-group
            = f.select :kind, options_for_select(ControlItem::KINDS, f.object.kind), {}, class: 'form-control'
        %td
          .form-group
            = f.text_field :name, class: 'form-control'
        %td
          .form-group
            = f.text_field :value, class: 'form-control'
        %td
          .form-group
            = f.text_field :api_endpoint, class: 'form-control'
        %td
          = link_to_remove_association "x", f, class: 'btn btn-sm btn-danger'

app/views/admin/device_types/_controls_table.html.haml
%table.table.table-striped
  %thead
    %tr
      %th Kind
      %th Name
      %th Value
      %th API
  %tbody
    - device_type.control_items.each do |control_item|
      %tr
        %td= control_item.kind
        %td= control_item.name
        %td= control_item.value
        %td
          - if control_item.api_endpoint.present?
            %span.glyphicon.glyphicon-check

app/views/admin/device_types/_form.html.haml
= form_for(@device_type) do |f|
  - if @device_type.errors.any?
    #error_explanation
      %h2
        = pluralize(@device_type.errors.count, "error")
        prohibited this device_type from being saved:
      %ul
        - @device_type.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :name
    %br/
    = f.text_field :name, class: 'form-control'
  %hr

  %h4 Controls
  .help-message
    %span.glyphicon.glyphicon-info-sign
    Value has following meaning:
    %ul
      %li for select it is a comma separated string of available options
      %li for button it is not used
      %li for slider it is not used
    %span.glyphicon.glyphicon-info-sign
    API Endpoint is a string build with HTTP verb and URL e.g. 'POST http://example.com/volume'

  #control-items
    = f.fields_for :control_items do |control_item|
      = render 'control_item_fields', f: control_item
    .links.pull-right
      = link_to_add_association f, :control_items, class: 'btn btn-info' do
        %span.glyphicon.glyphicon-plus
        Add control
  %br/
  .actions
    = f.submit 'Save', class: 'btn btn-success'

app/views/admin/device_types/edit.html.haml
%h1 Editing Device Type
= render 'form'

app/views/admin/device_types/index.html.haml
%h1 Device Types
%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Controls
      %th Devices
      %th Actions
  %tbody
    - @device_types.each do |device_type|
      %tr
        %td= device_type.name
        %td
          = render 'controls_table', device_type: device_type
        %td
          %ul
            - device_type.devices.each do |device|
              %li
                = link_to device.name, edit_device_path(device)
        %td
          .btn-group{ role: 'group' }
            = link_to 'Show/Edit', edit_device_type_path(device_type), class: 'btn btn-info'
            = link_to 'Destroy', device_type, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
%br/
.pull-right
  = link_to new_device_type_path, class: 'btn btn-success' do
    %span.glypicon.glyphicon-plus
    Add device type

app/views/admin/device_types/new.html.haml
%h1 New Device Type
= render 'form'

app/views/admin/devices/_form.html.haml
= form_for(@device) do |f|
  - if @device.errors.any?
    #error_explanation
      %h2
        = pluralize(@device.errors.count, "error")
        prohibited this device from being saved:
      %ul
        - @device.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :name
    %br/
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :ip_address
    %br/
    = f.text_field :ip_address, class: 'form-control'
  .form-group
    = f.label :device_type
    %br/
    = f.collection_select :device_type_id, DeviceType.all, :id, :name, {},  { class: 'form-control js-device-type-select' }
    %span.glyphicon.glyphicon-info-sign
    Changing Device Type requires saving Device before editing Controls
  %hr
  %h4 Controls
  - if @device.device_type
    - if @device.control_items?
      %table.table
        %thead
          %tr
            %th Control Type
            %th Control Name
            %th Control Value
            %th Control API Endpoint
        %tbody
          - @device.device_type.control_items.each do |control_item|
            %tr
              = render "admin/controls/#{control_item.kind}", control_item: control_item, control_item_value: @device.control_value_for(control_item)
    - else
      %span.glyphicon.glyphicon-info-sign
      Associated Device Type has no controls defined.
  - else
    %span.glyphicon.glyphicon-info-sign
    Controls can be adjusted after saving new Device
  .actions
    = f.submit 'Save', class: 'btn btn-success'

app/views/admin/devices/edit.html.haml
%h1 Editing Device
= render 'form'

app/views/admin/devices/index.html.haml
%h1 Devices
%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Ip Address
      %th Device Type
      %th Controls
      %th Actions
  %tbody
    - @devices.each do |device|
      %tr
        %td= device.name
        %td= device.ip_address
        %td
          = link_to device.device_type.name, edit_device_type_path(device.device_type)
        %td
          - device.device_type.control_items.each do |control_item|
            = control_item.name
            %br/
        %td
          .btn-group{role: 'group'}
            = link_to 'Show/Edit', edit_device_path(device), class: 'btn btn-info'
            = link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
%br/
.pull-right
  = link_to new_device_path, class: 'btn btn-success' do
    %span.glypicon.glyphicon-plus
    Add new device

app/views/admin/devices/new.html.haml
%h1 New Device
= render 'form'

app/views/devices/_form.html.haml
= form_for(@device) do |f|
  - if @device.errors.any?
    #error_explanation
      %h2
        = pluralize(@device.errors.count, "error")
        prohibited this device from being saved:
      %ul
        - @device.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :name
    %br/
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :ip_address
    %br/
    = f.text_field :ip_address, class: 'form-control'
  .form-group
    = f.label :device_type
    %br/
    = f.collection_select :device_type_id, DeviceType.all, :id, :name, class: 'form-control'
    %span.glyphicon.glyphicon-info-sign
    Changing Device Type requires saving Device before editing Controls
  %hr
  %h4 Controls
  - if @device.device_type
    - if @device.control_items?
      %table.table
        %thead
          %tr
            %th Control Type
            %th Control Name
            %th Control Value
        %tbody
          - @device.device_type.control_items.each do |control_item|
            %tr
              = render "controls/#{control_item.kind}", control_item: control_item, control_item_value: @device.control_value_for(control_item)
    - else
      %span.glyphicon.glyphicon-info-sign
      Associated Device Type has no controls defined.
  - else
    %span.glyphicon.glyphicon-info-sign
    Controls can be adjusted after saving new Device
  .actions
    = f.submit 'Save', class: 'btn btn-success'

app/views/frontend/_navbar.html.haml
%nav.navbar.navbar-inverse.navbar-static-top
  .container-fluid
    %ul.nav.navbar-nav
      %li
        %a
          Devices

app/views/frontend/controls/_button.html.haml
= control_item.name
%a.ui-btn.ui-btn-inline.ui-corner-all.button{ 'data-api-verb' => control_item.api_verb, 'data-api-endpoint' => control_item.api_url }
  = control_item.name

app/views/frontend/controls/_select.html.haml
= control_item.name
.select
  = select_tag("device[controls_state][#{control_item.name.parameterize}]", options_for_select(control_item.select_options, control_item_value))

app/views/frontend/controls/_slider.html.haml
= control_item.name
.slider
  = range_field_tag("device[controls_state][#{control_item.name.parameterize}]", control_item_value, in: 1..100)

app/views/frontend/devices/index.html.haml
#alert-popup{ 'data-role' => 'popup' }
  Ups, there was an issue when saving the data. Try again after refreshing the page.

#success-popup{ 'data-role' => 'popup' }
  Yay! Action performed successfully!

#devices{ 'data-role' => 'page'}
  - @devices.each do |device|
    %div{ id: "#{device.id}", 'data-role' => 'panel', 'data-position' => 'right'}
      %form{ action: app_device_path(device) }
        - device.device_type.control_items.each do |control_item|
          .ui-content{ 'data-role' => 'main' }
            %ul{ 'data-autodividers' => 'false', 'data-inset' => 'false', 'data-role' => 'listview' }
              = render "frontend/controls/#{control_item.kind}", control_item: control_item, control_item_value: device.control_value_for(control_item)
      %a.ui-btn.ui-btn-inline.ui-corner-all.ui-icon-delete.ui-btn-icon-left{ 'data-rel' => 'close', href: '#devices' } Close

  %div{ 'data-role' => 'header' }
    %h1 Devices

  .ui-content{ 'data-role' => 'main' }
    %ul{ 'data-autodividers' => 'false', 'data-inset' => 'true', 'data-role' => 'listview' }
      - @devices.each do |device|
        %li
          %a{ href: "##{device.id}" }
            = device.name

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default{role: "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => "#main-menu", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

    #main-menu.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to 'Devices', devices_url
        %li
          = link_to 'Devices Types', device_types_url
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to 'http://app.kalm.pl', { target: '_blank' } do
            %span.glyphicon.glyphicon-new-window
            Open Frontend App

  = render "layouts/messages"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Home Automation - Admin
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render 'admin/navbar'
    .container
      = yield

app/views/layouts/frontend.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title Home Automation - Frontend
    = stylesheet_link_tag    'frontend', media: 'all'
    = javascript_include_tag 'frontend'
    %link{:href => "https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css", :rel => "stylesheet"}/
    %script{:src => "https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"}

    = csrf_meta_tags
  %body
    = yield